when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: true


    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler: { collect: false }


